name: Build Android Kernel

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc libncurses5-dev libssl-dev ccache bison flex git

    - name: Clone Google GCC Toolchain 4.9 (AArch64)
      run: |
        git clone https://github.com/KudProject/aarch64-linux-android-4.9
        export PATH=$GITHUB_WORKSPACE/aarch64-linux-android-4.9/bin:$PATH

    - name: Ensure build script is executable
      run: chmod +x ./build_kernel.sh

    - name: Build kernel
      run: |
        export CROSS_COMPILE=aarch64-linux-android-4.9/bin/aarch64-linux-android-
        ./build_kernel.sh

    - name: Upload kernel image
      uses: actions/upload-artifact@v4
      with:
        name: Image
        path: |
          arch/arm64/boot/Image
          arch/arm64/boot/Image.gz

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          arch/arm64/boot/Image
          arch/arm64/boot/Image.gz
        token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
